load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "greeter",
    srcs = ["greeter.go"],
    importpath = "example.com/bazel-multilang-template/examples/go",
)

go_test(
    name = "greeter_test",
    srcs = ["greeter_test.go"],
    embed = [":greeter"],
)
